name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: gameflix
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/gameflix
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: password
      run: mvn clean package

    - name: Install MySQL client
      run: sudo app-get update && sudo app-get install -y mysql-client

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; then
            echo "MySQL is up"; break
          fi
          echo "Waiting for MySQL..."; sleep 2
        done

    - name: Build Docker image
      run: docker-compose build
